### ISSUE TITLE
Repository size

### ISSUE THREAD

**Issue by jonseddon** [MetOffice/cube_helper#16]
The repository is quite large (721 MB) because of the old data files that were in the repository but have now been removed (see `.git/objects`), but the old ones have been kept for the history. Is there any way to prune these from the history? I suspect not because then you don't have the full history. This isn't too much of a problem because these old large files aren't in the releases that most users will download.

**Comment by TheElectricFlock** [comment]
I've used "BFG repo-cleaner"  on a mirrored repo and now it's down to about 11.6 MB.
$git clone https://github.com/MetOffice/cube_helper.git
Cloning into 'cube_helper'...
remote: Enumerating objects: 1211, done.
remote: Counting objects: 100% (1211/1211), done.
remote: Compressing objects: 100% (974/974), done.
remote: Total 3080 (delta 666), reused 765 (delta 228), pack-reused 1869
Receiving objects: 100% (3080/3080), 11.66 MiB | 2.57 MiB/s, done.
Resolving deltas: 100% (2075/2075), done.
